#include "ProjectBuildConfig.h"

#include <QDebug>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QHash>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QProcess>
#include <QString>

// Returns map: executable target name -> full path to executable binary
QHash<QString, QString> getExecutablesFromCMakeFileAPI(const QString &buildDir) {
    QHash<QString, QString> executables;

    auto replyDir = QDir(buildDir + "/.cmake/api/v1/reply");
    if (!replyDir.exists()) {
        qWarning() << "Reply directory does not exist:" << replyDir.path();
        return executables;
    }

    auto files = replyDir.entryList({"target-*.json"}, QDir::Files);
    for (const auto &fileName : files) {
        QFile file(replyDir.filePath(fileName));
        if (!file.open(QIODevice::ReadOnly)) {
            qWarning() << "Failed to open target file:" << fileName;
            continue;
        }

        auto doc = QJsonDocument::fromJson(file.readAll());
        auto obj = doc.object();

        if (obj["type"].toString() != "EXECUTABLE") {
            continue;
        }

        auto artifacts = obj["artifacts"].toArray();
        if (artifacts.isEmpty()) {
            continue;
        }

        auto name = obj["name"].toString();
        auto path = artifacts[0].toObject()["path"].toString();

        executables.insert(name, path);
    }

    return executables;
}

bool ExecutableInfo::operator==(const ExecutableInfo &other) const {
    /* clang-format off */
    return
        this->name == other.name &&
        this->runDirectory == other.runDirectory &&
        this->executables == other.executables;
    /* clang-format on */
}

bool TaskInfo::operator==(const TaskInfo &other) const {
    /* clang-format off */
    return
        this->name == other.name &&
        this->command == other.command &&
        this->isBuild == other.isBuild &&
        this->runDirectory == other.runDirectory;
    /* clang-format on */
}

auto ProjectBuildConfig::tryGuessFromCMake(const QString &directory)
    -> std::shared_ptr<ProjectBuildConfig> {
    auto cmakeFileName = directory + QDir::separator() + "CMakeLists.txt";
    auto di = QFileInfo(directory);
    auto fi = QFileInfo(cmakeFileName);
    if (!fi.isReadable()) {
        return {};
    }

    auto value = std::make_shared<ProjectBuildConfig>();
    value->projectType = ProjectType::cmake;
    value->autoGenerated = true;
    value->name = di.baseName();
    value->sourceDir = directory;
    value->hideFilter = ".git;.vscode;.vs;build;dist";
    value->buildDir = "${source_directory}/build";

    {
        auto t = TaskInfo();
        t.name = "CMake (configure/Debug)";
        // clang-format off
        t.command = "mkdir -p ${build_directory}/.cmake/api/v1/query/ && "
                    "touch  ${build_directory}/.cmake/api/v1/query/codemodel-v2 && "
                    "cmake -S ${source_directory} -B ${build_directory} -DCMAKE_BUILD_TYPE=Debug --graphviz=${build_directory}/graph.dot";
        // clang-format on
        t.runDirectory = "${source_directory}";
        t.isBuild = true;
        value->tasksInfo.push_back(t);
    }
    {
        auto t = TaskInfo();
        t.name = "CMake (configure/Release)";
        t.command = "cmake -S ${source_directory} -B ${build_directory} -DCMAKE_BUILD_TYPE=Release "
                    "--graphviz=${build_directory}/graph.dot";
        t.runDirectory = "${source_directory}";
        t.isBuild = true;
        value->tasksInfo.push_back(t);
    }
    {
        auto t = TaskInfo();
        t.name = "CMake Build (parallel)";
        t.command = "cmake --build ${build_directory} --parallel";
        t.runDirectory = "${source_directory}";
        t.isBuild = true;
        value->tasksInfo.push_back(t);
    }
    {
        auto t = TaskInfo();
        t.name = "CMake Build (single thread)";
        t.command = "cmake --build ${build_directory}";
        t.runDirectory = "${source_directory}";
        t.isBuild = true;
        value->tasksInfo.push_back(t);
    }
    value->updateBinariesCMake();
    return value;
}

auto ProjectBuildConfig::tryGuessFromCargo(const QString &directory)
    -> std::shared_ptr<ProjectBuildConfig> {
    auto cargoFileName = directory + "/" + "Cargo.toml";
    auto di = QFileInfo(directory);
    auto fi = QFileInfo(cargoFileName);
    if (!fi.isReadable()) {
        return {};
    }

    auto value = std::make_shared<ProjectBuildConfig>();
    value->projectType = ProjectType::cargo;
    value->autoGenerated = true;
    value->name = di.baseName();
    value->sourceDir = directory;
    value->hideFilter = ".git;.vscode;target";
    value->buildDir = directory + "/target";

    {
        auto t = TaskInfo();
        t.name = "cargo build";
        t.runDirectory = "${source_directory}";
        t.command = "cargo build";
        t.isBuild = true;
        value->tasksInfo.push_back(t);
    }
    {
        auto t = TaskInfo();
        t.name = "cargo build (release)";
        t.runDirectory = "${source_directory}";
        t.command = "cargo build --release";
        t.isBuild = true;
        value->tasksInfo.push_back(t);
    }
    {
        auto t = TaskInfo();
        t.name = "cargo update";
        t.runDirectory = "${source_directory}";
        t.command = "cargo update";
        value->tasksInfo.push_back(t);
    }
    value->updateBinariesCargo();

    return value;
}

auto ProjectBuildConfig::tryGuessFromGo(const QString &directory)
    -> std::shared_ptr<ProjectBuildConfig> {
    auto gomodFileName = directory + "/" + "go.mod";
    auto di = QFileInfo(directory);
    auto fi = QFileInfo(gomodFileName);
    if (!fi.isReadable()) {
        return {};
    }

    auto value = std::make_shared<ProjectBuildConfig>();
    value->projectType = ProjectType::golang;
    value->autoGenerated = true;
    value->name = di.baseName();
    value->sourceDir = directory;
    value->hideFilter = ".git;.vscode;";
    value->buildDir = "";

    {
        auto t = TaskInfo();
        t.name = "go build";
        t.runDirectory = "${source_directory}";
        t.command = "go build";
        value->tasksInfo.push_back(t);
    }
    {
        auto t = TaskInfo();
        t.name = "go fix";
        t.runDirectory = "${source_directory}";
        t.command = "go fix";
        value->tasksInfo.push_back(t);
    }
    value->updateBinariesGo();
    return value;
}

std::shared_ptr<ProjectBuildConfig>
ProjectBuildConfig::tryGuessFromMeson(const QString &directory) {
    auto mesonBuildFile = directory + "/" + "meson.build";
    auto di = QFileInfo(directory);
    auto fi = QFileInfo(mesonBuildFile);
    if (!fi.isReadable()) {
        return {};
    }

    auto value = std::make_shared<ProjectBuildConfig>();
    value->projectType = ProjectType::meson;
    value->name = di.baseName();
    value->sourceDir = directory;
    value->hideFilter = ".git;.vscode;";
    value->buildDir = directory + "/mbuild"; // meson build?

    {
        auto t = TaskInfo();
        t.name = "meson setup";
        t.runDirectory = "${source_directory}";
        t.command = "meson setup ${build_directory}";
        t.isBuild = true;
        value->tasksInfo.push_back(t);
    }
    {
        auto t = TaskInfo();
        t.name = "meson build";
        t.runDirectory = "${source_directory}";
        t.command = "meson compile -C ${build_directory}";
        t.isBuild = true;
        value->tasksInfo.push_back(t);
    }
    {
        auto t = TaskInfo();
        t.name = "meson tests";
        t.runDirectory = "${source_directory}";
        t.command = "meson test  -C ${build_directory}";
        value->tasksInfo.push_back(t);
    }
    value->updateBinariesMeson();
    return value;
}

std::shared_ptr<ProjectBuildConfig>
ProjectBuildConfig::buildFromDirectory(const QString &directory) {
    auto configFileName = directory + QDir::separator() + "qtedit4.json";
    auto config = buildFromFile(configFileName);
    if (!config) {
        config = tryGuessFromCMake(directory);
    }
    if (!config) {
        config = tryGuessFromMeson(directory);
    }
    if (!config) {
        config = tryGuessFromCargo(directory);
    }
    if (!config) {
        config = tryGuessFromGo(directory);
    }
    if (!config) {
        config = std::make_shared<ProjectBuildConfig>();
        config->sourceDir = directory;
    }
    return config;
}

std::shared_ptr<ProjectBuildConfig> ProjectBuildConfig::buildFromFile(const QString &jsonFileName) {
    auto file = QFile();
    file.setFileName(jsonFileName);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return {};
    }

    auto value = std::shared_ptr<ProjectBuildConfig>();
    auto fi = QFileInfo(jsonFileName);
    auto json = QJsonDocument::fromJson(file.readAll());
    file.close();

    auto toHash = [](QJsonValueRef v) -> QHash<QString, QString> {
        QHash<QString, QString> hash;
        if (v.isObject()) {
            auto jsonObj = v.toObject();
            for (const auto &vv : jsonObj.keys()) {
                hash[vv] = jsonObj[vv].toString();
            }
        }
        return hash;
    };
    auto parseExecutables = [&toHash](QJsonValue v) -> QList<ExecutableInfo> {
        QList<ExecutableInfo> info;
        if (v.isArray()) {
            for (const auto &vv : v.toArray()) {
                ExecutableInfo execInfo;
                execInfo.name = vv.toObject().value("name").toString();
                execInfo.executables = toHash(vv.toObject()["executables"]);
                execInfo.runDirectory = vv.toObject()["runDirectory"].toString();
                info.push_back(execInfo);
            };
        }
        return info;
    };
    auto parseTasksInfo = [](QJsonValue v) -> QList<TaskInfo> {
        QList<TaskInfo> info;
        if (v.isArray()) {
            for (const auto &vv : v.toArray()) {
                auto obj = vv.toObject();
                TaskInfo taskInfo;
                taskInfo.name = obj["name"].toString();
                taskInfo.command = obj["command"].toString();
                taskInfo.runDirectory = obj["runDirectory"].toString();
                taskInfo.isBuild = obj["isBuild"].toBool(false);
                info.push_back(taskInfo);
            };
        }
        return info;
    };
    if (!json.isNull()) {
        value = std::make_shared<ProjectBuildConfig>();
        value->autoGenerated = false;
        value->sourceDir = fi.absolutePath();
        value->fileName = fi.absoluteFilePath();
        value->name = json["name"].toString();
        value->buildDir = json["build_directory"].toString();
        value->executables = parseExecutables(json["executables"]);
        value->tasksInfo = parseTasksInfo(json["tasks"]);

        value->activeExecutableName = json["activeExecutableName"].toString();
        value->activeTaskName = json["activeTaskName"].toString();
        value->displayFilter = json["displayFilter"].toString();
        value->hideFilter = json["hideFilter"].toString();

        if (value->name.isEmpty()) {
            value->name = fi.dir().dirName();
        }
    } else {
        qDebug() << "ProjectBuildConfig::buildFromFile: Loading file failed, malformed JSON?"
                 << jsonFileName;
    }
    return value;
}

bool ProjectBuildConfig::canLoadFile(const QString &filename) {
    auto fi = QFileInfo(filename);
    if (fi.fileName().compare("CMakeLists.txt", Qt::CaseInsensitive) == 0) {
        return true;
    }
    if (fi.fileName().compare("Cargo.toml", Qt::CaseInsensitive) == 0) {
        return true;
    }
    if (fi.fileName().compare("go.mod", Qt::CaseInsensitive) == 0) {
        return true;
    }
    if (fi.fileName().compare("qtedit4.json", Qt::CaseInsensitive) == 0) {
        return true;
    }
    return false;
}

auto ProjectBuildConfig::updateBinaries() -> void {
    switch (projectType) {
    case ProjectType::cmake:
        updateBinariesCMake();
        break;
    case ProjectType::cargo:
        updateBinariesCargo();
        break;
    case ProjectType::golang:
        updateBinariesGo();
        break;
    case ProjectType::meson:
        updateBinariesMeson();
        break;
    case ProjectType::unkown:
        break;
    }
}

auto ProjectBuildConfig::updateBinariesCMake() -> void {
#if 0    
    auto di = QFileInfo(this->sourceDir);
    auto e = ExecutableInfo();
    e.name = di.fileName();
    e.runDirectory = "${build_directory}";
    e.executables["windows"] = "${build_directory}/bin/" + e.name + ".exe";
    e.executables["linux"] = "${build_directory}/bin/" + e.name;
    this->executables.push_back(e);
#else
    this->executables.clear();
    auto buildDir = expand(this->buildDir);
    auto binaries = getExecutablesFromCMakeFileAPI(buildDir);
    for (const auto &[key, value] : binaries.asKeyValueRange()) {
        // qDebug() << "updateBinariesCMake2 => Key:" << key << "Value:" << value;
        auto e = ExecutableInfo();
        e.name = value;
        e.runDirectory = "${build_directory}";
        e.executables["windows"] = "${build_directory}/" + value;
        e.executables["linux"] = "${build_directory}/" + value;
        this->executables.push_back(e);
    }
#endif
}

auto ProjectBuildConfig::updateBinariesCargo() -> void {
    auto e = ExecutableInfo();
    e.name = "cargo run";
    e.runDirectory = "${source_directory}";
    e.executables["windows"] = "cargo run";
    e.executables["linux"] = "cargo run";
    this->executables.clear();
    this->executables.push_back(e);
}

auto ProjectBuildConfig::updateBinariesGo() -> void {
    auto e = ExecutableInfo();
    e.name = "go run";
    e.runDirectory = "${source_directory}";
    e.executables["windows"] = "go run ${source_directory}";
    e.executables["linux"] = "go run ${source_directory}";
    this->executables.clear();
    this->executables.push_back(e);
}

auto ProjectBuildConfig::updateBinariesMeson() -> void {
    auto findMesonExecutables = [](const QString &directory,
                                   const QString &buildDir) -> QHash<QString, QString> {
        auto fullBuildPath = buildDir;
        auto process = QProcess();
        process.start("meson", QStringList() << "introspect" << fullBuildPath << "--targets");
        process.waitForFinished();

        auto output = process.readAllStandardOutput();
        if (output.isEmpty()) {
            qCritical() << "No output from meson introspect.";
            return {};
        }

        auto parseError = QJsonParseError();
        auto doc = QJsonDocument::fromJson(output, &parseError);
        if (parseError.error != QJsonParseError::NoError) {
            qCritical() << "Failed to parse JSON:" << parseError.errorString();
            return {};
        }

        auto targets = doc.array();
        auto result = QHash<QString, QString>();
        for (auto value : targets) {
            QJsonObject obj = value.toObject();
            if (obj["type"].toString() == "executable") {
                auto name = obj["name"].toString();
                auto filenames = obj["filename"].toArray();
                if (!filenames.isEmpty()) {
                    auto fullPath = filenames.first().toString();
                    auto relativeToDir = QDir(directory).relativeFilePath(fullPath);
                    result.insert(name, relativeToDir);
                }
            }
        }
        return result;
    };

    auto executables = findMesonExecutables(this->sourceDir, this->buildDir);
    this->executables.clear();
    for (auto it = executables.constBegin(); it != executables.constEnd(); ++it) {
        auto name = it.key();
        auto path = it.value();
        auto e = ExecutableInfo();
        e.name = name;
        e.runDirectory = "${source_directory}";
        e.executables["windows"] = path + ".exe";
        e.executables["linux"] = path;
        this->executables.push_back(e);
    }
}

auto ProjectBuildConfig::saveToFile(const QString &jsonFileName) -> void {
    auto file = QFile(jsonFileName);
    if (!file.open(QIODevice::WriteOnly)) {
        qWarning() << "Failed to open file for writing:" << file.errorString();
        return;
    }

    auto jsonObj = QJsonObject();
    jsonObj["build_directory"] = buildDir;

    auto execsArray = QJsonArray();
    for (const auto &exec : std::as_const(executables)) {
        auto execObj = QJsonObject();
        execObj["name"] = exec.name;
        execObj["runDirectory"] = exec.runDirectory;

        auto execsDetailsObj = QJsonObject();
        for (auto it = exec.executables.constBegin(); it != exec.executables.constEnd(); ++it) {
            execsDetailsObj[it.key()] = it.value();
        }
        execObj["executables"] = execsDetailsObj;

        execsArray.append(execObj);
    }
    jsonObj["executables"] = execsArray;

    auto tasksArray = QJsonArray();
    for (const auto &task : std::as_const(tasksInfo)) {
        auto taskObj = QJsonObject();
        taskObj["name"] = task.name;
        taskObj["command"] = task.command;
        taskObj["runDirectory"] = task.runDirectory;
        taskObj["isBuild"] = task.isBuild;

        tasksArray.append(taskObj);
    }
    jsonObj["tasks"] = tasksArray;

    jsonObj["activeExecutableName"] = activeExecutableName;
    jsonObj["activeTaskName"] = activeTaskName;
    jsonObj["displayFilter"] = displayFilter;
    jsonObj["hideFilter"] = hideFilter;

    auto jsonDoc = QJsonDocument(jsonObj);
    file.write(jsonDoc.toJson());
    file.close();

    this->fileName = jsonFileName;
}

auto ProjectBuildConfig::findIndexOfTask(const QString &taskName) -> int {
    for (auto n = 0; n < tasksInfo.length(); n++) {
        auto &t = tasksInfo[n];
        if (t.name == taskName) {
            return n;
        }
    }
    return -1;
}

auto ProjectBuildConfig::findIndexOfExecutable(const QString &executableName) -> int {
    for (auto n = 0; n < executables.length(); n++) {
        auto &e = executables[n];
        if (e.name == executableName) {
            return n;
        }
    }
    return -1;
}

auto ProjectBuildConfig::getConfigDictionary() const -> const QHash<QString, QString> {
    auto dictionary = QHash<QString, QString>();
    dictionary["source_directory"] = QDir::toNativeSeparators(sourceDir);
    dictionary["build_directory"] = QDir::toNativeSeparators(buildDir);
    return dictionary;
}

auto ProjectBuildConfig::expand(const QString &input) -> QString {
    static auto regex = QRegularExpression(R"(\$\{([a-zA-Z0-9_]+)\})");
    auto output = input;
    auto depth = 0;
    auto maxDepth = 10;
    auto hashTable = getConfigDictionary();

    while (depth < maxDepth) {
        auto it = regex.globalMatch(output);
        if (!it.hasNext()) {
            break;
        }
        while (it.hasNext()) {
            auto match = it.next();
            auto key = match.captured(1);
            auto replacement = hashTable.value(key, "");
            output.replace(match.captured(0), replacement);
        }
        depth++;
    }
    return output;
}

bool ProjectBuildConfig::operator==(const ProjectBuildConfig &other) const {
    /* clang-format off */
    return sourceDir == other.sourceDir &&
           buildDir == other.buildDir &&
           executables == other.executables &&
           tasksInfo == other.tasksInfo &&
           activeExecutableName == other.activeExecutableName &&
           activeTaskName == other.activeTaskName &&
           displayFilter == other.displayFilter &&
           hideFilter == other.hideFilter &&
           fileName == other.fileName;
    /* clang-format on */
}
