name: Codespell

on:
  push:
    branches : ["main"]
  pull_request:
    branches : ["main"]

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: codespell-project/actions-codespell@master
      with:
        check_filenames: true
        path: ./src/
        skip: "*.lua,*.ui,./src/stb/stb_*.h"
        ignore_words_list: "doubleclick,msdos"
      
